### ISSUE TITLE
in-line sql

### ISSUE THREAD

**Issue by danmarsden** [wjunkin/moodle-mod_ipal#1]
HI Bill, 

here's some more detail around the in-line sql I mentioned earlier.

In-line SQL refers to placing variables directly into the sql statement like this:

`"SELECT * FROM {sometable} WHERE id = ". $var`

Typically you will sanitise $var so that it can't contain extra nasty SQL statements and allow a SQL injection to occur but Moodle also adds another layer of protection by passing parameters separately into the db function calls like this:

`$DB->get_records_sql("SELECT * FROM {sometable} WHERE id = ?", array($var));`

doing this completely protects $var from being able to contain any extra nasty sql statements.

An example of your code:
https://github.com/wjunkin/moodle-mod_ipal/blob/MOODLE_28_STABLE/ipal/lib.php#L215

```
        $query = "SELECT ra.userid FROM {role_assignments} ra, {context} cx
            WHERE ra.contextid = cx.id AND cx.instanceid = $courseid AND ra.roleid = $studentroleid AND cx.contextlevel = 50";
        $studentids = $DB->get_records_sql($query);
```

One option to replace that would be:
            $query = "SELECT ra.userid FROM {role_assignments} ra, {context} cx
                WHERE ra.contextid = cx.id AND cx.instanceid = ? AND ra.roleid = ? AND cx.contextlevel = 50";
            $studentids = $DB->get_records_sql($query, array($courseid, $studentroleid));

Then the array at the end list the params in the same order as the sql statement.

Some queries are quite complex and you don't want to use the order you populate the array so Moodle allows you to use named params like this as well:

```
        $query = "SELECT ra.userid FROM {role_assignments} ra, {context} cx
            WHERE ra.contextid = cx.id AND cx.instanceid = :courseid AND ra.roleid = :roleid AND cx.contextlevel = 50";
        $params = array();
        $params['courseid'] = $courseid;
        $params['roleid'] = $roleid;

        $studentids = $DB->get_records_sql($query, $params);
```

Hopefully that makes a bit more sense? There is also some more reading on this here:
https://docs.moodle.org/dev/SQL_coding_style

As a side note - I also noticed a couple of sql statements using $CFG->prefix before the table names - not a big deal but that dates back to Moodle 1.9 I think - the new way to do it is to just wrap the table name in {} -
 `SELECT * FROM '. $CFG->prefix.'tablename`
becomes 
 `SELECT * FROM {tablename}`

**Comment by wjunkin** [comment]
Thanks, Dan,
I think I have changed all the code in ipal to conform to this way of doing queries and thus protecting the program from inserting bad stuff. So, I am closing this issue.

**Comment by danmarsden** [comment]
great - a very quick look at some of the files looks like you've sorted this - (I haven't performed a complete review of all your code though) - great to see the improvements!
